Models/Facture.cs
using System.ComponentModel.DataAnnotations;

namespace facture.Models
{
    public class Facture
    {
        [Key]
        public int factureNumber {get;set;}
        
        [Required]
        public string designation {get;set;}

        [Required]
        
        public string reference {get;set;}
        [Required]
        
        public int quantite {get;set;}
        
        [Required]
        public double prix {get;set;}
        
        [Required]
        public int tva {get;set;}

        [Required]
        public int clientId {set; get;}
        public Client client;

        [Required]
        public string raisonSociale {get;set;}
        
    }
}

Pages/clients/create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using facture.Data;
using facture.Dtos;
using facture.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace facture.Pages.clients
{
    public class createModel : PageModel
    {
        private readonly FactureDbContext _db;
        
        [BindProperty]
        public ClientDto client {get; set;}
        
        public createModel(FactureDbContext db)
        {
            _db = db;
        }

        public async Task<ActionResult> OnPost()
        {
            if (ModelState.IsValid) {
                await _db.AddAsync((Client) client);
                await _db.SaveChangesAsync();

                return RedirectToPage("index");
            } else {
                return Page();
            }
        }
    }
}

Pages/clients/update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using facture.Data;
using facture.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace facture.Pages.clients
{
    public class updateModel : PageModel
    {

        private readonly FactureDbContext _db;

        [BindProperty]
        public Client client {get; set;}

        public updateModel(FactureDbContext db)
        {
            _db = db;
        }

        public async void OnGet(int id)
        {
            client = await _db.Clients.FindAsync(id);
        }

        public async Task<ActionResult> OnPost(int id)
        {
            if (ModelState.IsValid) {
                Client clnt = await _db.Clients.FindAsync(id);

                _db.Clients.Remove(clnt);
                
                await _db.AddAsync(client);

                await _db.SaveChangesAsync();

                return RedirectToPage("index");
            } else {
                return Page();
            }
        }
    }
}

Pages/factures/create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using facture.Data;
using facture.Dtos;
using facture.Models;
using Microsoft.EntityFrameworkCore;

namespace facture.Pages.factures
{
    public class createModel : PageModel
    {
        private readonly FactureDbContext _db;

        public createModel(FactureDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public FactureDto facture {get; set;}
        [BindProperty]
        public IList<Client> clientList {get;set;}

        public async Task OnGet()
        {   
            this.clientList = await _db.Clients.ToListAsync<Client>();
        }

        public async Task<ActionResult> OnPost()
        {
            if (ModelState.IsValid) {
                Client client = _db.Clients.FirstOrDefault(c => c.raisonSociale == facture.raisonSociale);
                if (client != null) {
                    Facture newFacture = new Facture(){
                        factureNumber = 0,
                        designation = facture.designation,
                        prix = facture.prix,
                        quantite = facture.quantite,
                        tva = facture.tva,
                        reference = facture.reference,
                        clientId = client.id,
                        raisonSociale = facture.raisonSociale
                    };

                    await _db.Factures.AddAsync(newFacture);
                    await _db.SaveChangesAsync();

                    return RedirectToPage("index");
                } else {
                    return Page();
                }
            } else {
                return Page();
            }
        }
    }
}

Pages/factures/index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using facture.Dtos;
using facture.Data;
using System.Text;
using facture.Models;

namespace facture.Pages.factures
{
    public class indexModel : PageModel
    {
        private readonly FactureDbContext _db;

        public indexModel(FactureDbContext db)
        {
            _db = db;
        }

        public IList<FactureDto> factureList {get; set;}

        public void OnGet()
        {
            factureList = new List<FactureDto>();

            foreach (var facture in _db.Factures.AsEnumerable())
            {
                FactureDto tmpFacture = new FactureDto {
                    factureNumber = facture.factureNumber,
                    designation = facture.designation,
                    prix = facture.prix,
                    quantite = facture.quantite,
                    tva = facture.tva,
                    reference = facture.reference,
                    montantHt = facture.prix * facture.quantite,
                    montantTva = facture.prix * facture.quantite * facture.tva / 100,
                    montantTtc = facture.prix * facture.quantite * ((double)facture.tva / 100 + 1),
                    clientId = facture.clientId,
                };

                factureList.Add(tmpFacture);
            }

        }

        public IActionResult OnPostExportCSV() {
            var builder = new StringBuilder();
            builder.AppendLine("Facture N,Client RS,Designation,Reference,Prix,Quantite,TVA,Montant HT,Montant TVA,Montant TTC");
            foreach (var f in _db.Factures.ToList<Facture>()){
                builder.AppendLine($"{f.factureNumber},{f.raisonSociale},{f.designation},{f.reference},{f.prix},{f.quantite},{f.tva},{f.prix * f.quantite},{f.prix * f.quantite * f.tva / 100},{f.prix * f.quantite * ((double)f.tva / 100 + 1)}");
            }
            return File(Encoding.UTF8.GetBytes(builder.ToString()), "text/csv", "facture.csv");
        }

        public async Task<ActionResult> OnPostDelete(int id) {
            var facture = await _db.Factures.FindAsync(id);
            _db.Factures.Remove(facture);
            await _db.SaveChangesAsync();
            
            return RedirectToPage("index");
        }
    }
}

Pages/factures/update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using facture.Data;
using facture.Dtos;
using facture.Models;
using Microsoft.EntityFrameworkCore;

namespace facture.Pages.factures
{


    public class updateModel : PageModel
    {
        private readonly FactureDbContext _db;

        public updateModel(FactureDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public FactureDto facture {get; set;}

        [BindProperty]
        public IList<Client> clientList {get;set;}

        public async Task<ActionResult> OnGet(int id)
        {
            var f = await _db.Factures.FindAsync(id);
            if (f == null) {
                return RedirectToPage("Error");
            } else {
                facture = new FactureDto {
                    factureNumber = f.factureNumber,
                    designation = f.designation,
                    prix = f.prix,
                    quantite = f.quantite,
                    tva = f.tva,
                    reference = f.reference,
                    raisonSociale = f.raisonSociale,
                };
                clientList = await _db.Clients.ToListAsync<Client>();
                return Page();
            }
        }

        public async Task<ActionResult> OnPost(int id, int clientId)
        {

            if (ModelState.IsValid) {

                Facture fac = await _db.Factures.FindAsync(id);

                Client newClient = await _db.Clients.FirstOrDefaultAsync(c => c.raisonSociale == fac.raisonSociale);
                
                _db.Factures.Remove(fac);

                await _db.Factures.AddAsync(new Facture(){
                    factureNumber = facture.factureNumber,
                    designation = facture.designation,
                    prix = facture.prix,
                    quantite = facture.quantite,
                    tva = facture.tva,
                    reference = facture.reference,
                    raisonSociale = newClient.raisonSociale,
                    clientId = newClient.id,
                });

                await _db.SaveChangesAsync();

                return RedirectToPage("index");
            } else {
                return Page();
            }
        }
    }
}

Pages/factures/create.cshtml
@page
@model facture.Pages.factures.createModel
@{
}

<br>
<h2 class="text-info">Nouveau Facture</h2>
<br>

<div class="border p-5 container">
    <form method="post">
        <div class="text-danger" asp-validation-summary="ModelOnly" ></div>
        <div class="row">
            <div class="col-6">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="facture.designation"></label>
                    </div>
                    <div class="col-6">
                        <input class="form-control" asp-for="facture.designation" />
                    </div>
                    <div class="mt-1 col-12">
                        <span class="text-danger" asp-validation-for="facture.designation" ></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="facture.reference"></label>
                    </div>
                    <div class="col-6">
                        <input class="form-control" asp-for="facture.reference" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="facture.tva"></label>
                    </div>
                    <div class="col-6">
                        <select class="form-control" asp-for="facture.tva" >
                            <option value="20">20%</option>
                            <option value="7">7%</option>
                        </select>
                    </div>
                </div>

            </div>
            <div class="col-6">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="facture.quantite"></label>
                    </div>
                    <div class="col-6">
                        <input class="form-control" asp-for="facture.quantite" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="facture.prix"></label>
                    </div>
                    <div class="col-6">
                        <input class="form-control" asp-for="facture.prix" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label >RS</label>
                    </div>
                    <div class="col-6">
                        <select class="form-control" asp-for="facture.raisonSociale" >
                        @foreach (var client in Model.clientList)
                        {
                            <option value="@client.raisonSociale">@client.raisonSociale</option>                            
                        }
                        </select>
                    </div>
                </div>

            </div>
            <div class="col-12 mt-4">
                <div class="form-group row text-center">
                    <div class="col-3 offset-3">
                        <input type="submit" value="Valider" class="btn btn-primary form-control" />
                    </div>
                    <div class="col-3">
                        <a asp-page="index" class="btn btn-danger form-control" >Annuler</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Pages/factures/index.cshtml
@page
@model facture.Pages.factures.indexModel
@{
    
}

<br/>
<div class="container row p-0 m-0">
    <div class="col-7">
        <h2 class="text-info">Factures</h2>
    </div>
    <form method="post" asp-page-handler="ExportCSV" class="d-flex col-5">
        <button type="submit" class="btn btn-success form-control text-white ml-3">Export CSV</button>
        <a asp-page="create" class="btn btn-info form-control text-white">Nouvelle Facture</a>
    </form>

    <div class="col-12 border p-3 mt-3">
        <form method="post">
            @if (Model.factureList.Count() > 0) {
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th>
                            <label >Client Id</label>
                        </th>
                        <th>
                            <label asp-for="factureList.FirstOrDefault().designation"></label>
                        </th>
                        <th>
                            <label asp-for="factureList.FirstOrDefault().prix"></label>
                        </th>
                        <th>
                            <label asp-for="factureList.FirstOrDefault().quantite"></label>
                        </th>
                        <th>
                            <label >Montant HT</label>
                        </th>
                        <th>
                            <label >Montant TVA</label>
                        </th>
                        <th>
                            <label >Total (TTC)</label>
                        </th>
                        <th>
                            <label asp-for="factureList.FirstOrDefault().reference"></label>
                        </th>
                    </tr>
                    @foreach (var facture in Model.factureList)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => facture.clientId)
                            </td>
                            <td>
                                @Html.DisplayFor(m => facture.designation)
                            </td>
                            <td>
                                @Html.DisplayFor(m => facture.prix)
                            </td>
                            <td>
                                @Html.DisplayFor(m => facture.quantite)
                            </td>
                            <td>
                                @Html.DisplayFor(m => (facture.montantHt))
                            </td>
                            <td>
                                @Html.DisplayFor(m => (facture.montantTva))
                            </td>
                            <td>
                                @Html.DisplayFor(m => (facture.montantTtc))
                            </td>
                            <td>
                                @Html.DisplayFor(m => facture.reference)
                            </td>
                            <td>
                                <button asp-page-handler="Delete" asp-route-id="@facture.factureNumber" onclick="return confirm('Est-ce-que vous etes sure?')" class="btn-danger btn btn-sm">Supprimer</button>
                                <a asp-page="update" asp-route-id="@facture.factureNumber" class="btn btn-light btn-sm">Modifier</a>
                            </td>
                        </tr>
                    }
                </table>
            } else {
                <p>Aucune Facture Trouvee</p>
            }
        </form>
    </div>
</div>

Pages/factures/update.cshtml
@page
@model facture.Pages.factures.updateModel
@{
}

<br>
<h2 class="text-info">Modifier Facture</h2>
<br>

<div class="border p-5 container">
    <form method="post" >
        <input type="hidden" asp-for="facture.factureNumber" />
        <div class="text-danger" asp-validation-summary="ModelOnly" ></div>
        <div class="row">
            <div class="col-6">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="facture.designation"></label>
                    </div>
                    <div class="col-6">
                        <input class="form-control" asp-for="facture.designation" />
                    </div>
                    <div class="mt-1 col-12">
                        <span class="text-danger" asp-validation-for="facture.designation" ></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="facture.reference"></label>
                    </div>
                    <div class="col-6">
                        <input class="form-control" asp-for="facture.reference" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="facture.tva"></label>
                    </div>
                    <div class="col-6">
                        <select class="form-control" asp-for="facture.tva" >
                            <option value="20">20%</option>
                            <option value="7">7%</option>
                        </select>
                    </div>
                </div>

            </div>
            <div class="col-6">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="facture.quantite"></label>
                    </div>
                    <div class="col-6">
                        <input class="form-control" asp-for="facture.quantite" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="facture.prix"></label>
                    </div>
                    <div class="col-6">
                        <input class="form-control" asp-for="facture.prix" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label >RS</label>
                    </div>
                    <div class="col-6">
                        <select class="form-control" asp-for="facture.raisonSociale" >
                        @foreach (var client in Model.clientList)
                        {
                            <option selected="facture.raisonSociale == @client.raisonSociale" value="@client.raisonSociale">@client.raisonSociale</option>                            
                        }
                        </select>
                    </div>
                </div>

            </div>

            <div class="col-12 mt-4">
                <div class="form-group row text-center">
                    <div class="col-3 offset-3">
                        <input type="submit" value="Modifier" class="btn btn-primary form-control" />
                    </div>
                    <div class="col-3">
                        <a asp-page="index" class="btn btn-danger form-control" >Annuler</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}